language: python

notifications:
  email:
    - jonathon@bnotions.com

python:
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get install -qq zookeeper

env:
    global:
        - ZOOKEEPER_PATH=/usr/share/java
    matrix:
        - KAZOO='kazoo>=0.5,<0.6'
        - KAZOO='kazoo>=0.6,<0.7'
        - KAZOO='kazoo>=0.7,<0.8'
        - KAZOO='kazoo>=0.8,<0.9'
        - KAZOO='kazoo>=0.9,<1.0'
        - KAZOO='kazoo>=1.0,<1.1'
        - KAZOO='kazoo>=1.1,<1.2.1'
        - KAZOO='kazoo>=1.2,<1.3.1'
        - KAZOO='kazoo>=1.3,<2.0'
        - DJANGO='Django>=1.2,<1.3'
        - DJANGO='Django>=1.3,<1.4'
        - DJANGO='Django>=1.4,<1.5'
        - DJANGO='Django>=1.5,<1.6'
        - DJANGO='Django>=1.6,<1.7'
        - DJANGO='Django>=1.7,<1.8'

install:
    - pip install --use-mirrors $KAZOO
    - pip install --use-mirrors $DJANGO

script: make test
